/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Type = "text";
export type Markdown = string;
export type Type1 = "table";
export type Columns = string[];
export type Rows = string[][];
export type Type2 = "gallery";
export type Url = string;
export type Caption = string | null;
/**
 * Page the image was found on, for attribution.
 */
export type SourceUrl = string | null;
export type Images = GalleryImage[];
export type Type3 = "chart";
export type Kind = "bar" | "line" | "pie";
export type Labels = string[];
export type Values = number[];
export type Title = string | null;
export type Type4 = "code";
export type Language = string;
export type Content = string;
export type Type5 = "sources";
export type Title1 = string;
export type Url1 = string;
export type Items = Source[];
export type Blocks = (TextBlock | TableBlock | GalleryBlock | ChartBlock | CodeBlock | SourcesBlock)[];
export type Event =
  TextDeltaEvent | BlockStartEvent | BlockDataEvent | AgentStatusEvent | AgentUpdateEvent | DoneEvent | ErrorEvent;
export type Event1 = "text_delta";
export type BlockId = string;
export type Text = string;
export type Event2 = "block_start";
export type BlockId1 = string;
export type BlockType = string;
export type Event3 = "block_data";
export type BlockId2 = string;
export type Block = TextBlock | TableBlock | GalleryBlock | ChartBlock | CodeBlock | SourcesBlock;
export type Event4 = "agent_status";
export type Message = string;
export type Event5 = "agent_update";
export type Id = string;
export type Label = string;
export type Status = string;
export type State = "running" | "done" | "error";
export type Event6 = "done";
export type Event7 = "error";
export type Message1 = string;

/**
 * Wrapper so one schema carries both halves of the contract + all $defs.
 */
export interface Contract {
  reply: Reply;
  event: Event;
  [k: string]: unknown;
}
/**
 * The orchestrator's final structured answer.
 */
export interface Reply {
  blocks: Blocks;
  [k: string]: unknown;
}
export interface TextBlock {
  type?: Type;
  markdown: Markdown;
  [k: string]: unknown;
}
export interface TableBlock {
  type?: Type1;
  columns: Columns;
  rows: Rows;
  [k: string]: unknown;
}
export interface GalleryBlock {
  type?: Type2;
  images: Images;
  [k: string]: unknown;
}
export interface GalleryImage {
  url: Url;
  caption?: Caption;
  source_url?: SourceUrl;
  [k: string]: unknown;
}
export interface ChartBlock {
  type?: Type3;
  kind: Kind;
  labels: Labels;
  values: Values;
  title?: Title;
  [k: string]: unknown;
}
export interface CodeBlock {
  type?: Type4;
  language: Language;
  content: Content;
  [k: string]: unknown;
}
/**
 * Citations — the proof behind a grounded answer.
 */
export interface SourcesBlock {
  type?: Type5;
  items: Items;
  [k: string]: unknown;
}
export interface Source {
  title: Title1;
  url: Url1;
  [k: string]: unknown;
}
export interface TextDeltaEvent {
  event?: Event1;
  block_id: BlockId;
  text: Text;
  [k: string]: unknown;
}
/**
 * Opens a block. Carries the type (and id) BEFORE any data — enables skeleton.
 */
export interface BlockStartEvent {
  event?: Event2;
  block_id: BlockId1;
  block_type: BlockType;
  [k: string]: unknown;
}
/**
 * Fills a previously-started block with its validated payload.
 */
export interface BlockDataEvent {
  event?: Event3;
  block_id: BlockId2;
  block: Block;
  [k: string]: unknown;
}
/**
 * Working heartbeat to fill dead air during multi-round-trip runs.
 */
export interface AgentStatusEvent {
  event?: Event4;
  message: Message;
  [k: string]: unknown;
}
/**
 * Lifecycle of an individual sub-agent — drives the live activity panel.
 *
 * The frontend merges by ``id``: ``label`` is set when the agent starts; later
 * updates carry ``status``/``state`` only.
 */
export interface AgentUpdateEvent {
  event?: Event5;
  id: Id;
  label?: Label;
  status?: Status;
  state?: State;
  [k: string]: unknown;
}
export interface DoneEvent {
  event?: Event6;
  [k: string]: unknown;
}
export interface ErrorEvent {
  event?: Event7;
  message: Message1;
  [k: string]: unknown;
}
