/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Type = "text";
export type Markdown = string;
export type Type1 = "table";
export type Columns = string[];
export type Rows = string[][];
export type Type2 = "gallery";
export type Url = string;
export type Caption = string | null;
/**
 * Page the image was found on, for attribution.
 */
export type SourceUrl = string | null;
export type Images = GalleryImage[];
export type Type3 = "chart";
export type Kind = "bar" | "line" | "area" | "pie" | "donut";
export type Labels = string[];
/**
 * Values for a single series (one per label).
 */
export type Values = number[];
/**
 * For comparisons: several named series (each one value per label); rendered with a legend.
 */
export type Series = ChartSeries[] | null;
export type Name = string;
export type Values1 = number[];
export type Title = string | null;
export type Type4 = "sim";
export type Title1 = string | null;
export type Kind1 = "line" | "area";
export type Label = string | null;
export type Min = number;
export type Max = number;
export type Unit = string | null;
/**
 * Sampling step for DISCRETE domains (1 for counts of things); omit for continuous.
 */
export type Step = number | null;
export type YLabel = string | null;
export type YUnit = string | null;
/**
 * @minItems 1
 * @maxItems 6
 */
export type Variables =
  | [SimVariable]
  | [SimVariable, SimVariable]
  | [SimVariable, SimVariable, SimVariable]
  | [SimVariable, SimVariable, SimVariable, SimVariable]
  | [SimVariable, SimVariable, SimVariable, SimVariable, SimVariable]
  | [SimVariable, SimVariable, SimVariable, SimVariable, SimVariable, SimVariable];
/**
 * Identifier used in expressions, e.g. 'r'. Letters/digits/_, must not be 'x'.
 */
export type Name1 = string;
/**
 * Human label shown next to the control, e.g. 'Interest rate'.
 */
export type Label1 = string;
export type Control = "slider" | "stepper" | "select" | "toggle";
export type Default = number;
export type Min1 = number | null;
export type Max1 = number | null;
export type Step1 = number | null;
/**
 * Shown after the value, e.g. '%', '°C', 'yr'.
 */
export type Unit1 = string | null;
/**
 * Required for control='select': the discrete choices.
 */
export type Options = SimOption[] | null;
export type Label2 = string;
export type Value = number;
/**
 * @minItems 1
 * @maxItems 6
 */
export type Series1 =
  | [SimSeries]
  | [SimSeries, SimSeries]
  | [SimSeries, SimSeries, SimSeries]
  | [SimSeries, SimSeries, SimSeries, SimSeries]
  | [SimSeries, SimSeries, SimSeries, SimSeries, SimSeries]
  | [SimSeries, SimSeries, SimSeries, SimSeries, SimSeries, SimSeries];
export type Name2 = string;
/**
 * Math expression over x and the variables, e.g. 'P*(1+r/100)^x'. Operators + - * / % ^, functions like sin/cos/exp/ln/sqrt (radians), constants pi/e.
 */
export type Expr = string;
export type Type5 = "timeline";
export type Title2 = string | null;
/**
 * Overall span label, e.g. '10,000 BC — 500 AD'.
 */
export type Range = string | null;
/**
 * @minItems 1
 * @maxItems 8
 */
export type Eras =
  | [TimelineEra]
  | [TimelineEra, TimelineEra]
  | [TimelineEra, TimelineEra, TimelineEra]
  | [TimelineEra, TimelineEra, TimelineEra, TimelineEra]
  | [TimelineEra, TimelineEra, TimelineEra, TimelineEra, TimelineEra]
  | [TimelineEra, TimelineEra, TimelineEra, TimelineEra, TimelineEra, TimelineEra]
  | [TimelineEra, TimelineEra, TimelineEra, TimelineEra, TimelineEra, TimelineEra, TimelineEra]
  | [TimelineEra, TimelineEra, TimelineEra, TimelineEra, TimelineEra, TimelineEra, TimelineEra, TimelineEra];
export type Name3 = string;
/**
 * Display range, e.g. '4000–1200 BC'.
 */
export type Range1 = string | null;
/**
 * @minItems 1
 */
export type Events = [TimelineEvent, ...TimelineEvent[]];
/**
 * Display label, e.g. '~3500 BC', 'May 2024'.
 */
export type Date = string;
/**
 * Numeric time for positioning on the minimap (year; negative for BC). Omit only if unknown — the minimap needs it.
 */
export type T = number | null;
export type Title3 = string;
/**
 * One-sentence description.
 */
export type Desc = string | null;
export type Type6 = "change";
export type Title4 = string | null;
/**
 * e.g. 'By age group · 2023–2026 · % of respondents'.
 */
export type Subtitle = string | null;
/**
 * Time points, e.g. ['2023','2024'].
 *
 * @minItems 2
 * @maxItems 12
 */
export type Periods =
  | [string, string]
  | [string, string, string]
  | [string, string, string, string]
  | [string, string, string, string, string]
  | [string, string, string, string, string, string]
  | [string, string, string, string, string, string, string]
  | [string, string, string, string, string, string, string, string]
  | [string, string, string, string, string, string, string, string, string]
  | [string, string, string, string, string, string, string, string, string, string]
  | [string, string, string, string, string, string, string, string, string, string, string]
  | [string, string, string, string, string, string, string, string, string, string, string, string];
/**
 * Segments, e.g. age groups.
 *
 * @minItems 1
 * @maxItems 8
 */
export type Groups =
  | [string]
  | [string, string]
  | [string, string, string]
  | [string, string, string, string]
  | [string, string, string, string, string]
  | [string, string, string, string, string, string]
  | [string, string, string, string, string, string, string]
  | [string, string, string, string, string, string, string, string];
/**
 * Answer categories, e.g. ['Support','Neutral','Oppose']; one entry for a plain metric.
 *
 * @minItems 1
 * @maxItems 5
 */
export type Options1 =
  | [string]
  | [string, string]
  | [string, string, string]
  | [string, string, string, string]
  | [string, string, string, string, string];
/**
 * data[period][group][option] — same order as the label lists.
 */
export type Data = number[][][];
/**
 * Index into options that the trend view plots.
 */
export type TrendOption = number;
/**
 * Value unit shown in labels.
 */
export type Unit2 = string;
export type Type7 = "code";
export type Language = string;
export type Content = string;
/**
 * Relative path/name when the code is a real file (enables download).
 */
export type Filename = string | null;
/**
 * Stable id of the code artifact this block is the latest version of.
 */
export type ArtifactId = string | null;
export type Type8 = "diagram";
/**
 * Valid Mermaid source, e.g. 'graph TD; A-->B'.
 */
export type Mermaid = string;
export type Title5 = string | null;
export type Type9 = "slides";
export type Title6 = string | null;
export type Title7 = string;
/**
 * Slide body as concise markdown — short bullets, not paragraphs.
 */
export type Markdown1 = string;
export type Slides = Slide[];
export type Type10 = "sources";
export type Title8 = string;
export type Url1 = string;
export type Items = Source[];
export type Blocks = (
  | TextBlock
  | TableBlock
  | GalleryBlock
  | ChartBlock
  | SimBlock
  | TimelineBlock
  | ChangeBlock
  | CodeBlock
  | DiagramBlock
  | SlidesBlock
  | SourcesBlock
)[];
export type Event =
  | TextDeltaEvent
  | BlockStartEvent
  | BlockDataEvent
  | AgentStatusEvent
  | AgentUpdateEvent
  | ImageQuotaEvent
  | DoneEvent
  | ErrorEvent;
export type Event1 = "text_delta";
export type BlockId = string;
export type Text = string;
export type Event2 = "block_start";
export type BlockId1 = string;
export type BlockType = string;
export type Event3 = "block_data";
export type BlockId2 = string;
export type Block =
  | TextBlock
  | TableBlock
  | GalleryBlock
  | ChartBlock
  | SimBlock
  | TimelineBlock
  | ChangeBlock
  | CodeBlock
  | DiagramBlock
  | SlidesBlock
  | EditsBlock
  | FileBlock
  | MapBlock
  | SourcesBlock;
export type Type11 = "edits";
export type ArtifactId1 = string;
export type Name4 = string | null;
export type Old = string;
export type New = string;
export type Changes = EditChange[];
export type Type12 = "file";
export type Name5 = string;
export type Url2 = string;
export type Mime = string;
export type Size = number;
export type Type13 = "map";
export type Name6 = string;
export type Lat = number;
export type Lon = number;
export type Points = MapPoint[];
export type DistanceKm = number | null;
export type DurationMin = number;
export type Mode = "car" | "bike" | "foot" | "transit";
export type Geometry = number[][];
export type Legs = MapLeg[] | null;
export type Mode1 = string;
export type Label3 = string | null;
export type Geometry1 = number[][];
export type Areas = MapArea[] | null;
export type Name7 = string;
export type Approximate = boolean;
export type Polygons = number[][][];
export type Title9 = string | null;
export type Event4 = "agent_status";
export type Message = string;
export type Event5 = "agent_update";
export type Id = string;
export type Label4 = string;
export type Status = string;
export type State = "running" | "done" | "error";
export type Event6 = "image_quota";
export type Used = number;
export type Remaining = number;
export type ResetsAt = string;
export type Event7 = "done";
export type InputTokens = number | null;
export type OutputTokens = number | null;
export type ContextWindow = number | null;
export type Models = string[];
export type Event8 = "error";
export type Message1 = string;

/**
 * Wrapper so one schema carries both halves of the contract + all $defs.
 */
export interface Contract {
  reply: Reply;
  event: Event;
  [k: string]: unknown;
}
/**
 * The orchestrator's final structured answer.
 */
export interface Reply {
  blocks: Blocks;
  [k: string]: unknown;
}
export interface TextBlock {
  type?: Type;
  markdown: Markdown;
  [k: string]: unknown;
}
export interface TableBlock {
  type?: Type1;
  columns: Columns;
  rows: Rows;
  [k: string]: unknown;
}
export interface GalleryBlock {
  type?: Type2;
  images: Images;
  [k: string]: unknown;
}
export interface GalleryImage {
  url: Url;
  caption?: Caption;
  source_url?: SourceUrl;
  [k: string]: unknown;
}
export interface ChartBlock {
  type?: Type3;
  kind: Kind;
  labels: Labels;
  values?: Values;
  series?: Series;
  title?: Title;
  [k: string]: unknown;
}
export interface ChartSeries {
  name: Name;
  values: Values1;
  [k: string]: unknown;
}
/**
 * An interactive simulation: curves defined by formulas over ``x`` plus
 * user-tunable variables. The frontend turns each variable into a control and
 * re-renders the curves live as the user plays with them.
 */
export interface SimBlock {
  type?: Type4;
  title?: Title1;
  kind?: Kind1;
  x: SimAxis;
  y_label?: YLabel;
  y_unit?: YUnit;
  variables: Variables;
  series: Series1;
  [k: string]: unknown;
}
/**
 * The input domain the curves are sampled over.
 */
export interface SimAxis {
  label?: Label;
  min: Min;
  max: Max;
  unit?: Unit;
  step?: Step;
  [k: string]: unknown;
}
/**
 * A tunable input of a simulation, rendered as a control.
 *
 * Control kinds: slider (bounded continuous range — rates, temperatures,
 * angles), stepper (integers / precise values via − + buttons), select
 * (discrete named choices), toggle (boolean, 0 or 1 in expressions).
 */
export interface SimVariable {
  name: Name1;
  label: Label1;
  control?: Control;
  default?: Default;
  min?: Min1;
  max?: Max1;
  step?: Step1;
  unit?: Unit1;
  options?: Options;
  [k: string]: unknown;
}
/**
 * One named choice of a select variable — the label the user sees and the
 * numeric value the expressions receive.
 */
export interface SimOption {
  label: Label2;
  value: Value;
  [k: string]: unknown;
}
export interface SimSeries {
  name: Name2;
  expr: Expr;
  [k: string]: unknown;
}
/**
 * A chronology: events in time, grouped into eras/periods.
 *
 * Renders as an interactive card — a minimap of all events on the time axis,
 * era chips for navigation, and a collapsible grouped list. For a short flat
 * chronology emit one era named after the whole span.
 */
export interface TimelineBlock {
  type?: Type5;
  title?: Title2;
  range?: Range;
  eras: Eras;
  [k: string]: unknown;
}
/**
 * A named period grouping events (collapsible section in the UI).
 */
export interface TimelineEra {
  name: Name3;
  range?: Range1;
  events: Events;
  [k: string]: unknown;
}
export interface TimelineEvent {
  date: Date;
  t?: T;
  title: Title3;
  desc?: Desc;
  [k: string]: unknown;
}
/**
 * How a value shifts across segments over time — e.g. opinion by age group
 * per year, adoption per demographic.
 *
 * ``data[period][group][option]`` is the value cube. With several options the
 * UI shows 100%-stacked bars per group (with per-period tabs and deltas) plus
 * a trend view of ``trend_option`` over the periods; with a single option the
 * bars scale against the largest value instead.
 */
export interface ChangeBlock {
  type?: Type6;
  title?: Title4;
  subtitle?: Subtitle;
  periods: Periods;
  groups: Groups;
  options: Options1;
  data: Data;
  trend_option?: TrendOption;
  unit?: Unit2;
  [k: string]: unknown;
}
export interface CodeBlock {
  type?: Type7;
  language: Language;
  content: Content;
  filename?: Filename;
  artifact_id?: ArtifactId;
  [k: string]: unknown;
}
/**
 * A Mermaid diagram authored by the model (flowcharts, sequences, ER, etc.).
 */
export interface DiagramBlock {
  type?: Type8;
  mermaid: Mermaid;
  title?: Title5;
  [k: string]: unknown;
}
/**
 * A presentation (slide deck) authored by the model, viewed slide by slide.
 */
export interface SlidesBlock {
  type?: Type9;
  title?: Title6;
  slides: Slides;
  [k: string]: unknown;
}
export interface Slide {
  title: Title7;
  markdown?: Markdown1;
  [k: string]: unknown;
}
/**
 * Citations — the proof behind a grounded answer.
 */
export interface SourcesBlock {
  type?: Type10;
  items: Items;
  [k: string]: unknown;
}
export interface Source {
  title: Title8;
  url: Url1;
  [k: string]: unknown;
}
export interface TextDeltaEvent {
  event?: Event1;
  block_id: BlockId;
  text: Text;
  [k: string]: unknown;
}
/**
 * Opens a block. Carries the type (and id) BEFORE any data — enables skeleton.
 */
export interface BlockStartEvent {
  event?: Event2;
  block_id: BlockId1;
  block_type: BlockType;
  [k: string]: unknown;
}
/**
 * Fills a previously-started block with its validated payload.
 */
export interface BlockDataEvent {
  event?: Event3;
  block_id: BlockId2;
  block: Block;
  [k: string]: unknown;
}
/**
 * The changes applied to a code artifact this turn (targeted edit).
 *
 * Tool-authored only — produced when write_code patches an artifact in place,
 * so the transcript keeps a readable record of what changed and the canvas
 * shows the result.
 */
export interface EditsBlock {
  type?: Type11;
  artifact_id: ArtifactId1;
  name?: Name4;
  changes: Changes;
  [k: string]: unknown;
}
/**
 * One applied search/replace hunk — enough to render a familiar diff.
 */
export interface EditChange {
  old: Old;
  new: New;
  [k: string]: unknown;
}
/**
 * A downloadable generated file (e.g. a PDF from make_document).
 *
 * Tool-authored only — the url points into the uploads store (owner-only).
 */
export interface FileBlock {
  type?: Type12;
  name: Name5;
  url: Url2;
  mime?: Mime;
  size?: Size;
  [k: string]: unknown;
}
/**
 * A map with resolved locations (and optionally a route between them).
 *
 * Never authored by the model directly — the ``show_map`` tool geocodes real
 * coordinates and records this block, so positions can't be hallucinated.
 */
export interface MapBlock {
  type?: Type13;
  points: Points;
  route?: MapRoute | null;
  areas?: Areas;
  title?: Title9;
  [k: string]: unknown;
}
export interface MapPoint {
  name: Name6;
  lat: Lat;
  lon: Lon;
  [k: string]: unknown;
}
export interface MapRoute {
  distance_km?: DistanceKm;
  duration_min: DurationMin;
  mode?: Mode;
  geometry: Geometry;
  legs?: Legs;
  [k: string]: unknown;
}
/**
 * One leg of a multi-modal route (e.g. a walk, then Bus 3).
 */
export interface MapLeg {
  mode: Mode1;
  label?: Label3;
  geometry: Geometry1;
  [k: string]: unknown;
}
/**
 * A shaded region on the map: a real OSM boundary, or an LLM-sketched
 * approximation (drawn dashed + labeled approximate).
 */
export interface MapArea {
  name: Name7;
  approximate?: Approximate;
  polygons: Polygons;
  [k: string]: unknown;
}
/**
 * Working heartbeat to fill dead air during multi-round-trip runs.
 */
export interface AgentStatusEvent {
  event?: Event4;
  message: Message;
  [k: string]: unknown;
}
/**
 * Lifecycle of an individual sub-agent — drives the live activity panel.
 *
 * The frontend merges by ``id``: ``label`` is set when the agent starts; later
 * updates carry ``status``/``state`` only.
 */
export interface AgentUpdateEvent {
  event?: Event5;
  id: Id;
  label?: Label4;
  status?: Status;
  state?: State;
  [k: string]: unknown;
}
/**
 * Emitted after an image generation when the user's weekly quota runs low
 * (≤10% left) — the client shows a quiet, dismissable toast. Never sent while
 * plenty of quota remains: limits stay invisible until they matter.
 */
export interface ImageQuotaEvent {
  event?: Event6;
  used: Used;
  remaining: Remaining;
  resets_at: ResetsAt;
  [k: string]: unknown;
}
export interface DoneEvent {
  event?: Event7;
  input_tokens?: InputTokens;
  output_tokens?: OutputTokens;
  context_window?: ContextWindow;
  models?: Models;
  [k: string]: unknown;
}
export interface ErrorEvent {
  event?: Event8;
  message: Message1;
  [k: string]: unknown;
}
