"""Document generation: markdown → a clean, print-quality PDF (WeasyPrint).

Powers the ``make_document`` tool. The style is deliberately quiet — good
typography, subtle rules, a small silly-chat footer — and lives here as the one
source of truth for generated-document looks.
"""

from __future__ import annotations

import hashlib
import uuid

import markdown as md
from sqlmodel import Session

from app.logging_setup import get_logger

log = get_logger("documents")

_CSS = """
@page {
    size: A4;
    margin: 22mm 18mm;
    @bottom-center {
        content: "made with silly-chat";
        font-size: 8pt;
        color: #999;
    }
    @bottom-right {
        content: counter(page) " / " counter(pages);
        font-size: 8pt;
        color: #999;
    }
}
body { font-family: "DejaVu Sans", "Symbola", sans-serif; font-size: 10.5pt; line-height: 1.55; color: #1a1a1a; }
h1 { font-size: 21pt; letter-spacing: -0.02em; margin: 0 0 4pt; }
.subtitle { color: #888; font-size: 9pt; margin: 0 0 14pt; }
hr.rule { border: none; border-top: 1.5pt solid #1a1a1a; margin: 0 0 16pt; }
h2 { font-size: 14pt; margin: 16pt 0 6pt; letter-spacing: -0.01em; }
h3 { font-size: 11.5pt; margin: 12pt 0 4pt; }
p { margin: 5pt 0; }
ul, ol { margin: 5pt 0; padding-left: 16pt; }
li { margin: 2.5pt 0; }
table { border-collapse: collapse; width: 100%; margin: 8pt 0; font-size: 9.5pt; }
th { text-align: left; border-bottom: 1.2pt solid #1a1a1a; padding: 4pt 6pt; }
td { border-bottom: 0.5pt solid #ccc; padding: 4pt 6pt; vertical-align: top; }
code { font-family: "DejaVu Sans Mono", "Symbola", monospace; font-size: 8.8pt; background: #f2f2f2; padding: 0.5pt 2.5pt; border-radius: 2pt; }
pre { background: #f6f6f6; border: 0.5pt solid #ddd; border-radius: 3pt; padding: 7pt 9pt; overflow-wrap: break-word; white-space: pre-wrap; }
pre code { background: none; padding: 0; }
blockquote { border-left: 2pt solid #ccc; margin: 6pt 0; padding: 1pt 0 1pt 10pt; color: #555; }
a { color: #0b57d0; text-decoration: none; }
strong { font-weight: 700; }
"""


def _normalize(text: str) -> str:
    return "".join(ch for ch in text.casefold() if ch.isalnum())


def render_pdf(title: str, content_markdown: str, subtitle: str = "") -> bytes:
    """Render a markdown document to PDF bytes with the house style."""
    from weasyprint import HTML

    # Models often repeat the title as the markdown's first heading — the layout
    # already renders the title, so drop the duplicate.
    lines = content_markdown.lstrip().split("\n")
    if lines and lines[0].startswith("#") and _normalize(lines[0].lstrip("# ")) == _normalize(title):
        content_markdown = "\n".join(lines[1:])

    body = md.markdown(
        content_markdown,
        extensions=["tables", "fenced_code", "sane_lists", "smarty"],
    )
    html = (
        f"<html><head><style>{_CSS}</style></head><body>"
        f"<h1>{md.util.code_escape(title)}</h1>"
        + (f'<p class="subtitle">{md.util.code_escape(subtitle)}</p>' if subtitle else "")
        + '<hr class="rule">'
        f"{body}</body></html>"
    )
    return HTML(string=html).write_pdf()


def store_export(
    session: Session, user_id: int, name: str, data: bytes, mime: str, ext: str,
    dk: bytes | None = None,
) -> str:
    """Store generated bytes in the uploads store (owner-only, TTL-swept, sealed
    under the owner's data key when available). Returns the id."""
    from app.auth import crypto
    from app.models import Upload
    from app.uploads import _path

    up = Upload(
        id=uuid.uuid4().hex, user_id=user_id, sha256=hashlib.sha256(data).hexdigest(),
        kind="export", mime=mime, ext=ext, size=len(data), name=name,
        enc=1 if dk is not None else 0,
    )
    path = _path(up)
    path.write_bytes(crypto.encrypt_bytes(dk, data) if dk is not None else data)
    session.add(up)
    session.commit()
    return up.id
